FROM node:16-alpine AS builder
WORKDIR /app
COPY ./backend ./
RUN yarn install
RUN yarn package
RUN chmod +x ./heartbeat-backend

FROM ubuntu:latest
LABEL app=HeartBeat
RUN groupadd -r nonroot && useradd --no-log-init -r -g nonroot nonroot
USER nonroot
WORKDIR /app
COPY --from=builder /app/heartbeat-backend ./
RUN mkdir ./csv/
EXPOSE 3001
CMD [ "./heartbeat-backend" ]