FROM node:16-alpine as builder
COPY ./frontend /app
WORKDIR /app
RUN yarn install && yarn build

FROM nginx:latest

WORKDIR /app
COPY --from=builder /app/dist/heartbeat-frontend /usr/share/nginx/html
COPY ./infra/nginx.conf /etc/nginx/nginx.conf
