FROM node:19-alpine as builder
COPY ./frontend /app
WORKDIR /app
RUN npm install -g pnpm && \
    pnpm install --store-dir=/pnpm-store && \
    pnpm build && \
    pnpm store prune --store-dir=/pnpm-store

FROM nginx:latest
LABEL app=Heartbeat
LABEL arch=Frontend
WORKDIR /app
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./infra/nginx.conf /etc/nginx/nginx.conf
