env:
  RETENTION_DAYS: "10"
steps:
  - label: ":lock: Shell check"
    command: ././buildkite/ops/check shell

  - label: ":lock: Security Check"
    command: ./.buildkite/ops/check security

  - label: ":rocket: Backend Check"
    command: ./.buildkite/ops/check backend

  - label: ":mag: Frontend License Check"
    commands: ./.buildkite/ops/check frontend-license

  - label: ":mag: Backend License Check"
    commands: ./.buildkite/ops/check backend-license
    plugins:
      - artifacts#v1.9.0:
          upload:
            - "backend/build/reports/dependency-license/**/*"
          name: "backend-license-report"
          expire_in: "${RETENTION_DAYS} days"
