env:
  RETENTION_DAYS: "10"

steps:
#  - label: ":lock: Security Check"
#    command: ./.buildkite/ops/check security
#
#  - label: ":rocket: Backend Check"
#    command: ./.buildkite/ops/check backend
#
#  - label: ":mag: Frontend License Check"
#    commands: ./.buildkite/ops/check frontend-license
#
#  - label: ":mag: Backend License Check"
#    commands: ./.buildkite/ops/check backend-license
#    plugins:
#      - artifacts#v1.9.0:
#          upload:
#            - "backend/build/reports/dependency-license/**/*"
#          name: "backend-license-report"
#          expire_in: "${RETENTION_DAYS} days"
#
#  - label: "build-frontend"
#    branches: main
#    depends_on: deploy-infra
#    command: ./.buildkite/ops/build frontend

#  - label: "build-backend"
#    branches: main
    # depends_on: deploy-infra
#    command: ./.buildkite/ops/build backend

#  - wait
#  - label: ":rocket: Deploy infra"
#    if:  build.branch == "main" && build.message =~ /\[infra\]/
#    env:
#      AWSHost: "$AWS_HOST"
#      AWSAccountId: "$AWS_ACCOUNT_ID"
#      AWSRegion: "$AWS_REGION"
#    command: ./.buildkite/ops/deploy infra

#  - label: "build-backend"
#    branches: main
#    command: ./.buildkite/ops/build backend

#  - label: ":rocket: Build Stub"
#    if:  build.branch == "main" && build.message =~ /\[stub\]/
#    command: ./.buildkite/ops/build stub

#  - label: "build-frontend"
#    branches: main
#    command: ./.buildkite/ops/build frontend

#  - label: ":rocket: Deploy Stub"
#    if:  build.branch == "main" && build.message =~ /\[stub\]/
#    command: ./.buildkite/ops/deploy stub

#  - wait
#  - label: ":rocket: Deploy prod"
#    branches: main
#    command: ./.buildkite/ops/deploy prod


#  - wait
#  - label: ":rocket: Deploy e2e"
#    branches: main
#    command: ./.buildkite/ops/deploy e2e

#  - wait
  - label: ":rocket: Run e2e test"
#        branches: main
    # env:
    #   APP_ORIGIN: "http://13.215.41.120:4321"
    # command: ./.buildkite/ops/check e2e
    plugins:
      - docker#v5.6.0:
          image: "cypress/included:10.0.0"
          always-pull: true
          environment:
            APP_ORIGIN: "http://13.215.41.120:4321"
          volumes:
            - "./frontend:e2e"
          workdir: /e2e
          command: ["pnpm", "run", "e2e"]


