env:
  RETENTION_DAYS: "10"
steps:
  - label: ":mag: Mock Server Build"
    command: ./.buildkite/ops/build mockserver

  - label: ":mag: Mock Server deploy"
    depends_on: ":mag: Mock Server Build"
    command: ./.buildkite/ops/deploy stub
