env:
  RETENTION_DAYS: "10"
steps:
  - label: ":lock: Shell check"
    command: ./ops/check.sh shell

  - label: ":lock: Security Check"
    command: ./ops/check.sh security

  - label: ":rocket: Backend Check"
    command: ./ops/check.sh backend

  - label: ":mag: Frontend License Check"
    commands: ./ops/check.sh frontend-license

  - label: ":mag: Backend License Check"
    commands: ./ops/check.sh backend-license
    plugins:
      - artifacts#v1.9.0:
          upload:
            - "backend/build/reports/dependency-license/**/*"
          name: "backend-license-report"
          expire_in: "${RETENTION_DAYS} days"
