FROM mcr.microsoft.com/playwright:latest

WORKDIR /app
ENV TZ=Asia/Shanghai
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install -g pnpm
RUN pnpm install @playwright/test
RUN pnpm exec playwright install msedge
RUN pnpm exec playwright install chrome
ENV E2E_TOKEN_JIRA=""
ENV E2E_TOKEN_BUILD_KITE=""
ENV E2E_TOKEN_GITHUB=""
ENV E2E_TOKEN_FLAG_AS_BLOCK_JIRA=""
