FROM mcr.microsoft.com/playwright:latest

WORKDIR /app
ENV TZ=Asia/Shanghai
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install -g pnpm
RUN pnpm install -g @playwright/test
RUN pnpm exec playwright install msedge
RUN pnpm exec playwright install chrome
