FROM mcr.microsoft.com/playwright:latest

ENV TZ=Asia/Shanghai
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /app
RUN npm install -g pnpm
RUN pnpm exec playwright install msedge
RUN pnpm exec playwright install chrome
