version: '3.4'
services:
  stubs:
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./:/home/stubby4j/data"
    container_name: stubby4j_jre11
    ports:
      - 4323:4323
      - 8882:8882
      - 8891:8891
      - 7445:7445
    environment:
      YAML_CONFIG: stubs.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 4323
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
