name: Deploy

on:
  workflow_run:
    workflows: 
      - Create and publish a image
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: cn-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Copy docker-compose to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          source: "./infra/docker-compose.yml"
          target: "./"

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_TAG: latest
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            docker-compose stop
            docker rmi -f $(docker image ls --filter label=app=HeartBeat -q)
            docker pull $REGISTRY/heartbeat_backend:$IMAGE_TAG
            docker pull $REGISTRY/heartbeat_frontend:$IMAGE_TAG
            docker-compose run -d