name: Docs
on:
  push:
    branches:
      - main
      - doc-as-code
  workflow_dispatch:

defaults:
  run:
    working-directory: ./docs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use lts Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install & Lint
        run: |
          npm install -g yarn
          yarn
          yarn lint
      - name: Build docs
        run: yarn build
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          publish_branch: gh-pages