name: Infra

on:
  push:
    branches: ["master"]

jobs:
  create-aws-resource:
    if: ${{ !contains(github.event.head_commit.message, '[infra]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: cn-north-1
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: HeartBeat
          template: ./infra/cloudformation.yml
          parameter-overrides: "GitHubOrg=au-heartbeat,RepositoryName=HeartBeat,AwsHost=${{ secrets.AWS_HOST }}"
          