name: Release

on:
  push:
    tags:
      - '*'
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Build
        run: ./gradlew clean build
      - uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: backend/build/libs/heartbeat-backend-0.0.1-SNAPSHOT.jar
          retention-days: ${{ vars.RETENTION_DAYS }}

  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: |
          pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: frontend/dist
          retention-days: ${{ vars.RETENTION_DAYS }}
  release:
    runs-on: ubuntu-latest
    needs:
      - build_frontend
      - build_backend
    steps:
      - uses: actions/checkout@v3
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-app
          path: ./${{ env.REPO_NAME }}-frontend
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-app
      - name: List
        run: |
          ls -a
      - name: Release
        id: build
        run: |
          mkdir ${{ env.REPO_NAME }}
          mv ./${{ env.REPO_NAME }}-frontend ${{ env.REPO_NAME }}
          mv heartbeat-backend-0.0.1-SNAPSHOT.jar ${{ env.REPO_NAME }}
          zip -r ${{ env.REPO_NAME }}-$(git tag --sort version:refname | tail -n 1).zip ${{ env.REPO_NAME }}
          ls
          echo "TAG_NAME=$(git tag --sort version:refname | tail -n 1)" >> "$GITHUB_ENV"
      - name: Upload zip file
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.REPO_NAME }}-${{ env.TAG_NAME }}.zip
