# name: Vulnerability
# 
# on:
  # push:
    # branches: ["*"]
  # pull_request:
    # branches: ["master"]
# 
# jobs:
  # build:
    # runs-on: ubuntu-latest
    # permissions:
      # security-events: write
    # steps:
      # - uses: actions/checkout@v3
        # with:
          # fetch-depth: 0
          # ref: ${{ github.head_ref }}
      # - name: Scan fs
        # run: |
          # docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            #  aquasec/trivy fs \
            #  --severity HIGH,CRITICAL \
            #  --exit-code 1 \
            #  ./
# 
      # - name: Run Trivy vulnerability scanner in repo mode
        # uses: aquasecurity/trivy-action@master
        # with:
          # scan-type: 'fs'
          # ignore-unfixed: true
          # format: 'template'
          # template: '@/contrib/sarif.tpl'
          # output: 'trivy-results.sarif'
          # severity: '*'
# 
      # - name: Upload Trivy scan results to GitHub Security tab
        # uses: github/codeql-action/upload-sarif@v2
        # with:
          # sarif_file: 'trivy-results.sarif'
          # category: fs
# 
      # - name: Run Trivy vulnerability scanner in IaC mode
        # uses: aquasecurity/trivy-action@master
        # with:
          # scan-type: 'config'
          # hide-progress: false
          # format: 'table'
          # exit-code: '1'
          # ignore-unfixed: true
          # severity: 'CRITICAL,HIGH'
# 
      # - name: Upload Trivy scan results to GitHub Security tab
        # uses: github/codeql-action/upload-sarif@v2
        # with:
          # sarif_file: 'trivy-results.sarif'
          # category: config